[build]
  publish = "client/build"
  command = "cd client && npm run build"
  
[build.environment]
  REACT_APP_SERVER_HOSTNAME = "https://quiz-app-backend-ck66.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
